<?xml version="1.0" encoding="UTF-8"?>
<tileset name="upscaled" tilewidth="32" tileheight="32" tilecount="70" columns="10">
 <image source="sheet.png" width="320" height="224"/>
 <tile id="0" type="Solid"/>
 <tile id="1" type="Solid"/>
 <tile id="2" type="Solid"/>
 <tile id="3" type="Solid"/>
 <tile id="4" type="Solid"/>
 <tile id="5" type="Solid"/>
 <tile id="6" type="Solid"/>
 <tile id="7" type="Empty"/>
 <tile id="8" type="Empty"/>
 <tile id="9" type="Empty"/>
 <tile id="10" type="Solid"/>
 <tile id="11" type="Solid"/>
 <tile id="12" type="Solid"/>
 <tile id="13" type="Solid"/>
 <tile id="14" type="Solid"/>
 <tile id="15" type="Solid"/>
 <tile id="16" type="Solid"/>
 <tile id="17" type="Empty"/>
 <tile id="18" type="Empty"/>
 <tile id="19" type="Empty"/>
 <tile id="20" type="Solid"/>
 <tile id="21" type="Solid"/>
 <tile id="22" type="Solid"/>
 <tile id="23" type="Solid"/>
 <tile id="24" type="Solid"/>
 <tile id="25" type="Solid"/>
 <tile id="26" type="Solid"/>
 <tile id="27" type="Empty"/>
 <tile id="28" type="Empty"/>
 <tile id="29" type="Empty"/>
 <tile id="30" type="Solid"/>
 <tile id="31" type="Solid"/>
 <tile id="32" type="Solid"/>
 <tile id="33" type="Solid"/>
 <tile id="34" type="Empty"/>
 <tile id="35" type="Solid"/>
 <tile id="36" type="Solid"/>
 <tile id="37" type="Empty"/>
 <tile id="38" type="Empty"/>
 <tile id="39" type="Empty"/>
 <tile id="40" type="Empty"/>
 <tile id="41" type="Empty"/>
 <tile id="42" type="Solid"/>
 <tile id="43" type="Solid"/>
 <tile id="44" type="Empty"/>
 <tile id="45" type="Empty"/>
 <tile id="46" type="Empty"/>
 <tile id="47" type="Empty"/>
 <tile id="48" type="Empty"/>
 <tile id="49" type="Empty"/>
 <tile id="50" type="Empty"/>
 <tile id="51" type="RightSlope"/>
 <tile id="52" type="Solid"/>
 <tile id="53" type="Solid"/>
 <tile id="54" type="Empty"/>
 <tile id="55" type="Empty"/>
 <tile id="56" type="Empty"/>
 <tile id="57" type="Empty"/>
 <tile id="58" type="Empty"/>
 <tile id="59" type="Empty"/>
 <tile id="60" type="Empty"/>
 <tile id="61" type="LeftSlope"/>
 <tile id="62" type="Solid"/>
 <tile id="63" type="Solid"/>
 <tile id="64" type="Empty"/>
 <tile id="65" type="Empty"/>
 <tile id="66" type="Empty"/>
 <tile id="67" type="Empty"/>
 <tile id="68" type="Empty"/>
 <tile id="69" type="Empty"/>
</tileset>
